# Generated by Django 3.2.16 on 2023-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='option',
        ),
        migrations.AddField(
            model_name='category',
            name='answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
