# Generated by Django 3.2.16 on 2023-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230512_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='questions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
