# Generated by Django 3.2.16 on 2023-05-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230512_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='step',
            field=models.BigIntegerField(default=0),
        ),
    ]
