# Generated by Django 4.2.1 on 2023-05-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatflow',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_bot.answer'),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_bot.option'),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_bot.question'),
        ),
    ]
